import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SessionWrapper from '../components/SessionWrapper'
import Navbar from '../components/Navbar'
import ClientSideStateRender from '@/components/ClientSideStateRender'
import Loading from '@/components/Loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
          <SessionWrapper>
            <Navbar/>
            {children}
            <ClientSideStateRender/>
          </SessionWrapper>
        </body>
    </html>
  )
}